// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjdimzbfbmcbrtwfwtug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqZGltemJmYm1jYnJ0d2Z3dHVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTQ1OTMsImV4cCI6MjA2OTE5MDU5M30.VROsn2ugnTdFQ9hrJAHHZOcqs4bsJa7-4gnMvYdhhQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});